# Generated by Django 4.2.20 on 2025-04-17 17:53

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to=files.models.file_upload_path)),
                (
                    "file_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("size", models.BigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=files.models.file_upload_path),
        ),
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stored_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_files",
                        to="files.storedfile",
                    ),
                ),
            ],
        ),
    ]
