# Generated by Django 4.2.20 on 2025-04-19 13:33

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_storedfile_alter_file_file_userfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfile", options={"ordering": ["-uploaded_at"]},
        ),
        migrations.RenameField(
            model_name="userfile", old_name="original_filename", new_name="filename",
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=files.models.file_upload_path),
        ),
    ]
