# Generated by Django 4.2.20 on 2025-04-19 13:33

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_userfile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storedfile", options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=files.models.file_upload_path),
        ),
    ]
