# Generated by Django 4.2.20 on 2025-04-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_alter_storedfile_options_alter_file_file"),
    ]

    operations = [
        migrations.DeleteModel(name="File",),
    ]
